// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module elasticDemux(	// src/main/scala/chext/elastic/Demux.scala:9:7
  input  [255:0] io_source_bits,	// src/main/scala/chext/elastic/Demux.scala:19:14
  input          io_source_valid,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output         io_source_ready,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output [255:0] io_sinks_0_bits,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output         io_sinks_0_valid,	// src/main/scala/chext/elastic/Demux.scala:19:14
  input          io_sinks_0_ready,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output [255:0] io_sinks_1_bits,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output         io_sinks_1_valid,	// src/main/scala/chext/elastic/Demux.scala:19:14
  input          io_sinks_1_ready,	// src/main/scala/chext/elastic/Demux.scala:19:14
                 io_select_bits,	// src/main/scala/chext/elastic/Demux.scala:19:14
                 io_select_valid,	// src/main/scala/chext/elastic/Demux.scala:19:14
  output         io_select_ready	// src/main/scala/chext/elastic/Demux.scala:19:14
);

  wire valid = io_select_valid & io_source_valid;	// src/main/scala/chext/elastic/Demux.scala:29:40
  wire fire = valid & (io_select_bits ? io_sinks_1_ready : io_sinks_0_ready);	// src/main/scala/chext/elastic/Demux.scala:29:40, :30:28
  assign io_source_ready = fire;	// src/main/scala/chext/elastic/Demux.scala:9:7, :30:28
  assign io_sinks_0_bits = io_source_bits;	// src/main/scala/chext/elastic/Demux.scala:9:7
  assign io_sinks_0_valid = valid & ~io_select_bits;	// src/main/scala/chext/elastic/Demux.scala:9:7, :29:40, :37:{23,31}
  assign io_sinks_1_bits = io_source_bits;	// src/main/scala/chext/elastic/Demux.scala:9:7
  assign io_sinks_1_valid = valid & io_select_bits;	// src/main/scala/chext/elastic/Demux.scala:9:7, :29:40, :37:23
  assign io_select_ready = fire;	// src/main/scala/chext/elastic/Demux.scala:9:7, :30:28
endmodule

module StreamSplitter_Basic_256_256(	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
  input          clock,	// <stdin>:39:11
                 reset,	// <stdin>:40:11
  output         input_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:39:17
  input          input_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:39:17
  input  [383:0] input_TDATA,	// src/main/scala/accel/bugra/StreamSplitter.scala:39:17
  input          outputs_0_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
  output         outputs_0_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
  output [255:0] outputs_0_TDATA,	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
  input          outputs_1_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
  output         outputs_1_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
  output [255:0] outputs_1_TDATA	// src/main/scala/accel/bugra/StreamSplitter.scala:41:7
);

  wire _fork0_demux0_io_source_ready;	// src/main/scala/accel/bugra/StreamSplitter.scala:49:25
  wire _fork0_demux0_io_select_ready;	// src/main/scala/accel/bugra/StreamSplitter.scala:49:25
  reg  fork0_regs_0;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
  reg  fork0_regs_1;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
  wire fork0_ready_qual1_0 = _fork0_demux0_io_source_ready | fork0_regs_0;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21, :49:25
  wire fork0_ready_qual1_1 = _fork0_demux0_io_select_ready | fork0_regs_1;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21, :49:25
  wire fork0_ready = fork0_ready_qual1_0 & fork0_ready_qual1_1;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
  always @(posedge clock) begin	// <stdin>:39:11
    if (reset) begin	// <stdin>:39:11
      fork0_regs_0 <= 1'h0;	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7, :46:21
      fork0_regs_1 <= 1'h0;	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7, :46:21
    end
    else begin	// <stdin>:39:11
      fork0_regs_0 <= fork0_ready_qual1_0 & input_TVALID & ~fork0_ready;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
      fork0_regs_1 <= fork0_ready_qual1_1 & input_TVALID & ~fork0_ready;	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
        fork0_regs_0 = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7, :46:21
        fork0_regs_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7, :46:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  elasticDemux fork0_demux0 (	// src/main/scala/accel/bugra/StreamSplitter.scala:49:25
    .io_source_bits   (input_TDATA[255:0]),	// src/main/scala/accel/bugra/StreamSplitter.scala:50:24
    .io_source_valid  (input_TVALID & ~fork0_regs_0),	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
    .io_source_ready  (_fork0_demux0_io_source_ready),
    .io_sinks_0_bits  (outputs_0_TDATA),
    .io_sinks_0_valid (outputs_0_TVALID),
    .io_sinks_0_ready (outputs_0_TREADY),
    .io_sinks_1_bits  (outputs_1_TDATA),
    .io_sinks_1_valid (outputs_1_TVALID),
    .io_sinks_1_ready (outputs_1_TREADY),
    .io_select_bits   (input_TDATA[352]),	// src/main/scala/accel/bugra/StreamSplitter.scala:49:25
    .io_select_valid  (input_TVALID & ~fork0_regs_1),	// src/main/scala/accel/bugra/StreamSplitter.scala:46:21
    .io_select_ready  (_fork0_demux0_io_select_ready)
  );
  assign input_TREADY = fork0_ready;	// src/main/scala/accel/bugra/StreamSplitter.scala:34:7, :46:21
endmodule

module StreamSplitter_256_256(	// src/main/scala/accel/bugra/StreamSplitter.scala:67:7
  input          clock,	// <stdin>:112:11
                 reset,	// <stdin>:113:11
  output         input_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:76:17
  input          input_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:76:17
  input  [383:0] input_TDATA,	// src/main/scala/accel/bugra/StreamSplitter.scala:76:17
  input          outputs_0_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
  output         outputs_0_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
  output [255:0] outputs_0_TDATA,	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
  input          outputs_1_TREADY,	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
  output         outputs_1_TVALID,	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
  output [255:0] outputs_1_TDATA	// src/main/scala/accel/bugra/StreamSplitter.scala:78:7
);

  StreamSplitter_Basic_256_256 dut (	// src/main/scala/accel/bugra/StreamSplitter.scala:74:19
    .clock            (clock),
    .reset            (reset),
    .input_TREADY     (input_TREADY),
    .input_TVALID     (input_TVALID),
    .input_TDATA      (input_TDATA),
    .outputs_0_TREADY (outputs_0_TREADY),
    .outputs_0_TVALID (outputs_0_TVALID),
    .outputs_0_TDATA  (outputs_0_TDATA),
    .outputs_1_TREADY (outputs_1_TREADY),
    .outputs_1_TVALID (outputs_1_TVALID),
    .outputs_1_TDATA  (outputs_1_TDATA)
  );
endmodule

