// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module SteerLeft(	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:6:7
  input  [127:0] dataIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:13:18
  input          offsetIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:14:20
  output [255:0] dataOut	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:15:19
);

  assign dataOut = offsetIn ? {dataIn, 128'h0} : {128'h0, dataIn};	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:6:7, :21:10, :25:11
endmodule

module UpSize_Basic_128_256(	// src/main/scala/accel/bugra/UpSize.scala:33:7
  input          clock,	// <stdin>:44:11
                 reset,	// <stdin>:45:11
  output         input_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:38:17
  input          input_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:38:17
  input  [127:0] input_TDATA,	// src/main/scala/accel/bugra/UpSize.scala:38:17
  input          output_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:39:18
  output         output_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:39:18
  output [255:0] output_TDATA	// src/main/scala/accel/bugra/UpSize.scala:39:18
);

  wire [255:0] _transducer0_steerLeft_dataOut;	// src/main/scala/accel/bugra/UpSize.scala:43:27
  reg  [255:0] transducer0_register;	// src/main/scala/accel/bugra/UpSize.scala:44:27
  reg          transducer0_offset;	// src/main/scala/accel/bugra/UpSize.scala:45:25
  wire         _transducer0_nextOffset_T = transducer0_offset - 1'h1;	// src/main/scala/accel/bugra/UpSize.scala:45:25, :46:29
  wire [255:0] output_TDATA_0 = transducer0_register | _transducer0_steerLeft_dataOut;	// src/main/scala/accel/bugra/UpSize.scala:43:27, :44:27, :50:21
  wire         _transducer0_WIRE = input_TVALID & ~_transducer0_nextOffset_T;	// src/main/scala/accel/bugra/UpSize.scala:41:27, :46:29, :53:{24,33}
  wire         _transducer0_WIRE_1 = input_TVALID & _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/UpSize.scala:41:27, :46:29, :53:33
  wire [1:0]   transducer0_cond = {_transducer0_WIRE_1, _transducer0_WIRE};	// src/main/scala/accel/bugra/UpSize.scala:41:27, :53:33
  wire         transducer0_errorAtLeastTwoActions =
    input_TVALID
    & (|(transducer0_cond & {_transducer0_WIRE_1, _transducer0_WIRE} - 2'h1));	// src/main/scala/accel/bugra/UpSize.scala:41:27, :53:33
  wire         transducer0_errorNoAction = input_TVALID & transducer0_cond == 2'h0;	// src/main/scala/accel/bugra/UpSize.scala:41:27
  `ifndef SYNTHESIS	// src/main/scala/accel/bugra/UpSize.scala:41:27
    always @(posedge clock) begin	// src/main/scala/accel/bugra/UpSize.scala:41:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:41:27
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// src/main/scala/accel/bugra/UpSize.scala:41:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE
          & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:41:27, :53:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[src/main/scala/accel/bugra/UpSize.scala 41:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:41:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE_1
          & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:41:27, :53:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'consume' @[src/main/scala/accel/bugra/UpSize.scala 41:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:41:27
      if ((`PRINTF_COND_) & transducer0_errorNoAction & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:41:27
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[src/main/scala/accel/bugra/UpSize.scala 41:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:41:27
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// <stdin>:44:11
    if (reset) begin	// <stdin>:44:11
      transducer0_register <= 256'h0;	// src/main/scala/accel/bugra/UpSize.scala:44:27
      transducer0_offset <= 1'h0;	// src/main/scala/accel/bugra/UpSize.scala:45:25
    end
    else if (input_TVALID) begin	// src/main/scala/accel/bugra/UpSize.scala:38:17
      if (_transducer0_nextOffset_T) begin	// src/main/scala/accel/bugra/UpSize.scala:46:29
        transducer0_register <= output_TDATA_0;	// src/main/scala/accel/bugra/UpSize.scala:44:27, :50:21
        transducer0_offset <= _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/UpSize.scala:45:25, :46:29
      end
      else begin	// src/main/scala/accel/bugra/UpSize.scala:46:29
        if (output_TREADY)	// src/main/scala/accel/bugra/UpSize.scala:39:18
          transducer0_register <= 256'h0;	// src/main/scala/accel/bugra/UpSize.scala:44:27
        transducer0_offset <= ~output_TREADY & transducer0_offset;	// src/main/scala/accel/bugra/UpSize.scala:45:25, :54:16, :56:18
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/accel/bugra/UpSize.scala:33:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:33:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:33:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/accel/bugra/UpSize.scala:33:7
      automatic logic [31:0] _RANDOM[0:8];	// src/main/scala/accel/bugra/UpSize.scala:33:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/UpSize.scala:33:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/UpSize.scala:33:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/accel/bugra/UpSize.scala:33:7
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/accel/bugra/UpSize.scala:33:7
        end	// src/main/scala/accel/bugra/UpSize.scala:33:7
        transducer0_register =
          {_RANDOM[4'h0],
           _RANDOM[4'h1],
           _RANDOM[4'h2],
           _RANDOM[4'h3],
           _RANDOM[4'h4],
           _RANDOM[4'h5],
           _RANDOM[4'h6],
           _RANDOM[4'h7]};	// src/main/scala/accel/bugra/UpSize.scala:33:7, :44:27
        transducer0_offset = _RANDOM[4'h8][0];	// src/main/scala/accel/bugra/UpSize.scala:33:7, :45:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:33:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:33:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SteerLeft transducer0_steerLeft (	// src/main/scala/accel/bugra/UpSize.scala:43:27
    .dataIn   (input_TDATA),
    .offsetIn (transducer0_offset),	// src/main/scala/accel/bugra/UpSize.scala:45:25
    .dataOut  (_transducer0_steerLeft_dataOut)
  );
  assign input_TREADY = input_TVALID & (_transducer0_nextOffset_T | output_TREADY);	// src/main/scala/accel/bugra/UpSize.scala:33:7, :41:27, :46:29, :53:33, :54:16, :59:17
  assign output_TVALID = input_TVALID & ~_transducer0_nextOffset_T;	// src/main/scala/accel/bugra/UpSize.scala:33:7, :41:27, :46:29, :53:{24,33}, :54:16, :59:17
  assign output_TDATA = output_TDATA_0;	// src/main/scala/accel/bugra/UpSize.scala:33:7, :50:21
endmodule

module UpSize_128_256(	// src/main/scala/accel/bugra/UpSize.scala:70:7
  input          clock,	// <stdin>:131:11
                 reset,	// <stdin>:132:11
  output         input_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:77:17
  input          input_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:77:17
  input  [127:0] input_TDATA,	// src/main/scala/accel/bugra/UpSize.scala:77:17
  input          output_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:78:18
  output         output_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:78:18
  output [255:0] output_TDATA	// src/main/scala/accel/bugra/UpSize.scala:78:18
);

  UpSize_Basic_128_256 dut (	// src/main/scala/accel/bugra/UpSize.scala:75:20
    .clock         (clock),
    .reset         (reset),
    .input_TREADY  (input_TREADY),
    .input_TVALID  (input_TVALID),
    .input_TDATA   (input_TDATA),
    .output_TREADY (output_TREADY),
    .output_TVALID (output_TVALID),
    .output_TDATA  (output_TDATA)
  );
endmodule

