// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module SteerRight(	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:28:7
  input  [255:0] dataIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:34:18
  input          offsetIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:35:20
  output [127:0] dataOut	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:36:19
);

  assign dataOut = offsetIn ? dataIn[255:128] : dataIn[127:0];	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:28:7, :42:13, :46:11
endmodule

module DownSize_Basic_256_128(	// src/main/scala/accel/bugra/DownSize.scala:32:7
  input          clock,	// <stdin>:42:11
                 reset,	// <stdin>:43:11
  output         input_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:37:17
  input          input_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:37:17
  input  [255:0] input_TDATA,	// src/main/scala/accel/bugra/DownSize.scala:37:17
  input          output_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:38:18
  output         output_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:38:18
  output [127:0] output_TDATA	// src/main/scala/accel/bugra/DownSize.scala:38:18
);

  reg        transducer0_offset;	// src/main/scala/accel/bugra/DownSize.scala:42:25
  wire       _transducer0_nextOffset_T = transducer0_offset - 1'h1;	// src/main/scala/accel/bugra/DownSize.scala:42:25, :43:29
  wire       _transducer0_WIRE = input_TVALID & ~_transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:40:27, :43:29, :50:{24,33}
  wire       _transducer0_WIRE_1 = input_TVALID & _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:40:27, :43:29, :50:33
  wire [1:0] transducer0_cond = {_transducer0_WIRE_1, _transducer0_WIRE};	// src/main/scala/accel/bugra/DownSize.scala:40:27, :50:33
  wire       transducer0_errorAtLeastTwoActions =
    input_TVALID
    & (|(transducer0_cond & {_transducer0_WIRE_1, _transducer0_WIRE} - 2'h1));	// src/main/scala/accel/bugra/DownSize.scala:40:27, :50:33
  wire       transducer0_errorNoAction = input_TVALID & transducer0_cond == 2'h0;	// src/main/scala/accel/bugra/DownSize.scala:40:27
  `ifndef SYNTHESIS	// src/main/scala/accel/bugra/DownSize.scala:40:27
    always @(posedge clock) begin	// src/main/scala/accel/bugra/DownSize.scala:40:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:40:27
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// src/main/scala/accel/bugra/DownSize.scala:40:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE
          & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:40:27, :50:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[src/main/scala/accel/bugra/DownSize.scala 40:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:40:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE_1
          & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:40:27, :50:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'produce' @[src/main/scala/accel/bugra/DownSize.scala 40:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:40:27
      if ((`PRINTF_COND_) & transducer0_errorNoAction & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:40:27
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[src/main/scala/accel/bugra/DownSize.scala 40:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:40:27
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// <stdin>:42:11
    if (reset)	// <stdin>:42:11
      transducer0_offset <= 1'h0;	// src/main/scala/accel/bugra/DownSize.scala:32:7, :42:25
    else if (input_TVALID) begin	// src/main/scala/accel/bugra/DownSize.scala:37:17
      if (_transducer0_nextOffset_T) begin	// src/main/scala/accel/bugra/DownSize.scala:43:29
        if (output_TREADY)	// src/main/scala/accel/bugra/DownSize.scala:38:18
          transducer0_offset <= _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:42:25, :43:29
      end
      else	// src/main/scala/accel/bugra/DownSize.scala:43:29
        transducer0_offset <= ~output_TREADY & transducer0_offset;	// src/main/scala/accel/bugra/DownSize.scala:42:25, :51:16, :52:18
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/accel/bugra/DownSize.scala:32:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:32:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:32:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/accel/bugra/DownSize.scala:32:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/accel/bugra/DownSize.scala:32:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/DownSize.scala:32:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/DownSize.scala:32:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/accel/bugra/DownSize.scala:32:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/accel/bugra/DownSize.scala:32:7
        transducer0_offset = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/accel/bugra/DownSize.scala:32:7, :42:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:32:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:32:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SteerRight transducer0_steerRight (	// src/main/scala/accel/bugra/DownSize.scala:41:28
    .dataIn   (input_TDATA),
    .offsetIn (transducer0_offset),	// src/main/scala/accel/bugra/DownSize.scala:42:25
    .dataOut  (output_TDATA)
  );
  assign input_TREADY = input_TVALID & ~_transducer0_nextOffset_T & output_TREADY;	// src/main/scala/accel/bugra/DownSize.scala:32:7, :40:27, :43:29, :50:{24,33}, :51:16, :55:17
  assign output_TVALID = input_TVALID;	// src/main/scala/accel/bugra/DownSize.scala:32:7
endmodule

module DownSize_256_128(	// src/main/scala/accel/bugra/DownSize.scala:65:7
  input          clock,	// <stdin>:125:11
                 reset,	// <stdin>:126:11
  output         input_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:72:17
  input          input_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:72:17
  input  [255:0] input_TDATA,	// src/main/scala/accel/bugra/DownSize.scala:72:17
  input          output_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:73:18
  output         output_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:73:18
  output [127:0] output_TDATA	// src/main/scala/accel/bugra/DownSize.scala:73:18
);

  DownSize_Basic_256_128 dut (	// src/main/scala/accel/bugra/DownSize.scala:70:19
    .clock         (clock),
    .reset         (reset),
    .input_TREADY  (input_TREADY),
    .input_TVALID  (input_TVALID),
    .input_TDATA   (input_TDATA),
    .output_TREADY (output_TREADY),
    .output_TVALID (output_TVALID),
    .output_TDATA  (output_TDATA)
  );
endmodule

