// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// external module chext_mem_1w1r

module SteerLeft(	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:6:7
  input  [127:0] dataIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:13:18
  input  [1:0]   offsetIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:14:20
  output [511:0] dataOut	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:15:19
);

  wire [3:0][511:0] _GEN =
    {{{dataIn, 384'h0}},
     {{128'h0, dataIn, 256'h0}},
     {{256'h0, dataIn, 128'h0}},
     {{384'h0, dataIn}}};	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:21:10, :25:11
  assign dataOut = _GEN[offsetIn];	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:6:7, :25:11
endmodule

module UpSize_Basic_128_512(	// src/main/scala/accel/bugra/UpSize.scala:35:7
  input          clock,	// <stdin>:91:11
                 reset,	// <stdin>:92:11
  output         input_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:53:17
  input          input_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:53:17
  input  [127:0] input_TDATA,	// src/main/scala/accel/bugra/UpSize.scala:53:17
  input          output_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:54:18
  output         output_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:54:18
  output [511:0] output_TDATA	// src/main/scala/accel/bugra/UpSize.scala:54:18
);

  wire [127:0] transducer0_leftBuffer0_sink_bits;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  wire [511:0] _transducer0_steerLeft_dataOut;	// src/main/scala/accel/bugra/UpSize.scala:58:27
  wire [127:0] transducer0_leftBuffer0_source_bits = input_TDATA;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  wire         transducer0_leftBuffer0_source_valid = input_TVALID;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  reg          transducer0_leftBuffer0_wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          transducer0_leftBuffer0_wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          transducer0_leftBuffer0_maybe_full;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  wire         transducer0_leftBuffer0_ptr_match =
    transducer0_leftBuffer0_wrap == transducer0_leftBuffer0_wrap_1;	// src/main/scala/accel/bugra/UpSize.scala:43:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire         transducer0_leftBuffer0_source_ready;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  wire         transducer0_leftBuffer0_do_enq =
    transducer0_leftBuffer0_source_ready & transducer0_leftBuffer0_source_valid;	// src/main/scala/accel/bugra/UpSize.scala:43:21
  wire         transducer0_leftBuffer0_sink_valid =
    ~(transducer0_leftBuffer0_ptr_match & ~transducer0_leftBuffer0_maybe_full);	// src/main/scala/accel/bugra/UpSize.scala:43:21
  assign transducer0_leftBuffer0_source_ready =
    ~(transducer0_leftBuffer0_ptr_match & transducer0_leftBuffer0_maybe_full);	// src/main/scala/accel/bugra/UpSize.scala:43:21
  reg  [511:0] transducer0_register;	// src/main/scala/accel/bugra/UpSize.scala:59:27
  reg  [1:0]   transducer0_offset;	// src/main/scala/accel/bugra/UpSize.scala:60:25
  wire [1:0]   _transducer0_nextOffset_T = transducer0_offset + 2'h1;	// src/main/scala/accel/bugra/UpSize.scala:60:25, :61:29
  wire [511:0] output_TDATA_0 = transducer0_register | _transducer0_steerLeft_dataOut;	// src/main/scala/accel/bugra/UpSize.scala:58:27, :59:27, :65:21
  wire         _transducer0_WIRE =
    transducer0_leftBuffer0_sink_valid & ~(|_transducer0_nextOffset_T);	// src/main/scala/accel/bugra/UpSize.scala:43:21, :56:27, :61:29, :68:{24,33}
  wire         _transducer0_WIRE_1 =
    transducer0_leftBuffer0_sink_valid & (|_transducer0_nextOffset_T);	// src/main/scala/accel/bugra/UpSize.scala:43:21, :56:27, :61:29, :68:{24,33}
  wire         transducer0_leftBuffer0_sink_ready =
    transducer0_leftBuffer0_sink_valid & ((|_transducer0_nextOffset_T) | output_TREADY);	// src/main/scala/accel/bugra/UpSize.scala:43:21, :56:27, :61:29, :68:{24,33}, :69:16, :74:17
  wire [1:0]   transducer0_cond = {_transducer0_WIRE_1, _transducer0_WIRE};	// src/main/scala/accel/bugra/UpSize.scala:56:27, :68:33
  wire         transducer0_errorAtLeastTwoActions =
    transducer0_leftBuffer0_sink_valid
    & (|(transducer0_cond & {_transducer0_WIRE_1, _transducer0_WIRE} - 2'h1));	// src/main/scala/accel/bugra/UpSize.scala:43:21, :56:27, :68:33
  wire         transducer0_errorNoAction =
    transducer0_leftBuffer0_sink_valid & transducer0_cond == 2'h0;	// src/main/scala/accel/bugra/UpSize.scala:43:21, :56:27, :60:25
  `ifndef SYNTHESIS	// src/main/scala/accel/bugra/UpSize.scala:56:27
    always @(posedge clock) begin	// src/main/scala/accel/bugra/UpSize.scala:56:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:56:27
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// src/main/scala/accel/bugra/UpSize.scala:56:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE
          & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:56:27, :68:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[src/main/scala/accel/bugra/UpSize.scala 56:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:56:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE_1
          & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:56:27, :68:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'consume' @[src/main/scala/accel/bugra/UpSize.scala 56:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:56:27
      if ((`PRINTF_COND_) & transducer0_errorNoAction & ~reset)	// src/main/scala/accel/bugra/UpSize.scala:56:27
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[src/main/scala/accel/bugra/UpSize.scala 56:27]\n");	// src/main/scala/accel/bugra/UpSize.scala:56:27
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// <stdin>:91:11
    if (reset) begin	// <stdin>:91:11
      transducer0_leftBuffer0_wrap <= 1'h0;	// src/main/scala/chext/elastic/Queue.scala:148:19, src/main/scala/chisel3/util/Counter.scala:61:40
      transducer0_leftBuffer0_wrap_1 <= 1'h0;	// src/main/scala/chext/elastic/Queue.scala:148:19, src/main/scala/chisel3/util/Counter.scala:61:40
      transducer0_leftBuffer0_maybe_full <= 1'h0;	// src/main/scala/accel/bugra/UpSize.scala:43:21, src/main/scala/chext/elastic/Queue.scala:148:19
      transducer0_register <= 512'h0;	// src/main/scala/accel/bugra/UpSize.scala:59:27
      transducer0_offset <= 2'h0;	// src/main/scala/accel/bugra/UpSize.scala:60:25
    end
    else begin	// <stdin>:91:11
      automatic logic transducer0_leftBuffer0_do_deq =
        transducer0_leftBuffer0_sink_ready & transducer0_leftBuffer0_sink_valid;	// src/main/scala/accel/bugra/UpSize.scala:43:21
      if (transducer0_leftBuffer0_do_enq)	// src/main/scala/accel/bugra/UpSize.scala:43:21
        transducer0_leftBuffer0_wrap <= transducer0_leftBuffer0_wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (transducer0_leftBuffer0_do_deq)	// src/main/scala/accel/bugra/UpSize.scala:43:21
        transducer0_leftBuffer0_wrap_1 <= transducer0_leftBuffer0_wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(transducer0_leftBuffer0_do_enq == transducer0_leftBuffer0_do_deq))	// src/main/scala/accel/bugra/UpSize.scala:43:21
        transducer0_leftBuffer0_maybe_full <= transducer0_leftBuffer0_do_enq;	// src/main/scala/accel/bugra/UpSize.scala:43:21
      if (transducer0_leftBuffer0_sink_valid) begin	// src/main/scala/accel/bugra/UpSize.scala:43:21
        if (|_transducer0_nextOffset_T) begin	// src/main/scala/accel/bugra/UpSize.scala:61:29, :68:24
          transducer0_register <= output_TDATA_0;	// src/main/scala/accel/bugra/UpSize.scala:59:27, :65:21
          transducer0_offset <= _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/UpSize.scala:60:25, :61:29
        end
        else if (output_TREADY) begin	// src/main/scala/accel/bugra/UpSize.scala:54:18
          transducer0_register <= 512'h0;	// src/main/scala/accel/bugra/UpSize.scala:59:27
          transducer0_offset <= 2'h0;	// src/main/scala/accel/bugra/UpSize.scala:60:25
        end
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/accel/bugra/UpSize.scala:35:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:35:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:35:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/accel/bugra/UpSize.scala:35:7
      automatic logic [31:0] _RANDOM[0:16];	// src/main/scala/accel/bugra/UpSize.scala:35:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/UpSize.scala:35:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/UpSize.scala:35:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/accel/bugra/UpSize.scala:35:7
        for (logic [4:0] i = 5'h0; i < 5'h11; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/accel/bugra/UpSize.scala:35:7
        end	// src/main/scala/accel/bugra/UpSize.scala:35:7
        transducer0_leftBuffer0_wrap = _RANDOM[5'h0][0];	// src/main/scala/accel/bugra/UpSize.scala:35:7, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_leftBuffer0_wrap_1 = _RANDOM[5'h0][1];	// src/main/scala/accel/bugra/UpSize.scala:35:7, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_leftBuffer0_maybe_full = _RANDOM[5'h0][2];	// src/main/scala/accel/bugra/UpSize.scala:35:7, :43:21, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_register =
          {_RANDOM[5'h0][31:3],
           _RANDOM[5'h1],
           _RANDOM[5'h2],
           _RANDOM[5'h3],
           _RANDOM[5'h4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7],
           _RANDOM[5'h8],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE],
           _RANDOM[5'hF],
           _RANDOM[5'h10][2:0]};	// src/main/scala/accel/bugra/UpSize.scala:35:7, :59:27, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_offset = _RANDOM[5'h10][4:3];	// src/main/scala/accel/bugra/UpSize.scala:35:7, :59:27, :60:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:35:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/UpSize.scala:35:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(128)
  ) transducer0_leftBuffer0_ram (	// src/main/scala/accel/bugra/UpSize.scala:43:21
    .clock    (clock),
    .addrA    (transducer0_leftBuffer0_wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (transducer0_leftBuffer0_do_enq),	// src/main/scala/accel/bugra/UpSize.scala:43:21
    .dataInA  (transducer0_leftBuffer0_source_bits),	// src/main/scala/accel/bugra/UpSize.scala:43:21
    .addrB    (transducer0_leftBuffer0_wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (transducer0_leftBuffer0_sink_bits)
  );
  SteerLeft transducer0_steerLeft (	// src/main/scala/accel/bugra/UpSize.scala:58:27
    .dataIn   (transducer0_leftBuffer0_sink_bits),	// src/main/scala/accel/bugra/UpSize.scala:43:21
    .offsetIn (transducer0_offset),	// src/main/scala/accel/bugra/UpSize.scala:60:25
    .dataOut  (_transducer0_steerLeft_dataOut)
  );
  assign input_TREADY = transducer0_leftBuffer0_source_ready;	// src/main/scala/accel/bugra/UpSize.scala:35:7, :43:21
  assign output_TVALID =
    transducer0_leftBuffer0_sink_valid & ~(|_transducer0_nextOffset_T);	// src/main/scala/accel/bugra/UpSize.scala:35:7, :43:21, :56:27, :61:29, :68:{24,33}, :69:16, :74:17
  assign output_TDATA = output_TDATA_0;	// src/main/scala/accel/bugra/UpSize.scala:35:7, :65:21
endmodule

module UpSize_128_512(	// src/main/scala/accel/bugra/UpSize.scala:85:7
  input          clock,	// <stdin>:230:11
                 reset_n,	// <stdin>:231:11
  output         input_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:92:17
  input          input_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:92:17
  input  [127:0] input_TDATA,	// src/main/scala/accel/bugra/UpSize.scala:92:17
  input          output_TREADY,	// src/main/scala/accel/bugra/UpSize.scala:93:18
  output         output_TVALID,	// src/main/scala/accel/bugra/UpSize.scala:93:18
  output [511:0] output_TDATA	// src/main/scala/accel/bugra/UpSize.scala:93:18
);

  wire          reset = ~reset_n;	// <stdin>:221:20
  UpSize_Basic_128_512 dut (	// src/main/scala/accel/bugra/UpSize.scala:90:20
    .clock         (clock),
    .reset         (reset),
    .input_TREADY  (input_TREADY),
    .input_TVALID  (input_TVALID),
    .input_TDATA   (input_TDATA),
    .output_TREADY (output_TREADY),
    .output_TVALID (output_TVALID),
    .output_TDATA  (output_TDATA)
  );
endmodule

