// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// external module chext_mem_1w1r

module SteerRight(	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:28:7
  input  [255:0] dataIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:34:18
  input          offsetIn,	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:35:20
  output [127:0] dataOut	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:36:19
);

  assign dataOut = offsetIn ? dataIn[255:128] : dataIn[127:0];	// src/main/scala/chext/amba/axi4/full/components/helpers/Steer.scala:28:7, :42:13, :46:11
endmodule

module DownSize_Basic_256_128(	// src/main/scala/accel/bugra/DownSize.scala:34:7
  input          clock,	// <stdin>:83:11
                 reset,	// <stdin>:84:11
  output         input_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:39:17
  input          input_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:39:17
  input  [255:0] input_TDATA,	// src/main/scala/accel/bugra/DownSize.scala:39:17
  input          output_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:40:18
  output         output_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:40:18
  output [127:0] output_TDATA	// src/main/scala/accel/bugra/DownSize.scala:40:18
);

  wire [255:0] transducer0_leftBuffer0_sink_bits;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  wire [255:0] transducer0_leftBuffer0_source_bits = input_TDATA;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  wire         transducer0_leftBuffer0_source_valid = input_TVALID;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  reg          transducer0_leftBuffer0_wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          transducer0_leftBuffer0_wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          transducer0_leftBuffer0_maybe_full;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  wire         transducer0_leftBuffer0_ptr_match =
    transducer0_leftBuffer0_wrap == transducer0_leftBuffer0_wrap_1;	// src/main/scala/accel/bugra/DownSize.scala:44:21, src/main/scala/chisel3/util/Counter.scala:61:40
  wire         transducer0_leftBuffer0_source_ready;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  wire         transducer0_leftBuffer0_do_enq =
    transducer0_leftBuffer0_source_ready & transducer0_leftBuffer0_source_valid;	// src/main/scala/accel/bugra/DownSize.scala:44:21
  wire         transducer0_leftBuffer0_sink_valid =
    ~(transducer0_leftBuffer0_ptr_match & ~transducer0_leftBuffer0_maybe_full);	// src/main/scala/accel/bugra/DownSize.scala:44:21
  assign transducer0_leftBuffer0_source_ready =
    ~(transducer0_leftBuffer0_ptr_match & transducer0_leftBuffer0_maybe_full);	// src/main/scala/accel/bugra/DownSize.scala:44:21
  reg          transducer0_offset;	// src/main/scala/accel/bugra/DownSize.scala:59:25
  wire         _transducer0_nextOffset_T = transducer0_offset - 1'h1;	// src/main/scala/accel/bugra/DownSize.scala:59:25, :60:29
  wire         _transducer0_WIRE =
    transducer0_leftBuffer0_sink_valid & ~_transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:44:21, :54:27, :60:29, :67:{24,33}
  wire         _transducer0_WIRE_1 =
    transducer0_leftBuffer0_sink_valid & _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:44:21, :54:27, :60:29, :67:33
  wire         transducer0_leftBuffer0_sink_ready =
    transducer0_leftBuffer0_sink_valid & ~_transducer0_nextOffset_T & output_TREADY;	// src/main/scala/accel/bugra/DownSize.scala:44:21, :54:27, :60:29, :67:{24,33}, :68:16, :72:17
  wire [1:0]   transducer0_cond = {_transducer0_WIRE_1, _transducer0_WIRE};	// src/main/scala/accel/bugra/DownSize.scala:54:27, :67:33
  wire         transducer0_errorAtLeastTwoActions =
    transducer0_leftBuffer0_sink_valid
    & (|(transducer0_cond & {_transducer0_WIRE_1, _transducer0_WIRE} - 2'h1));	// src/main/scala/accel/bugra/DownSize.scala:44:21, :54:27, :67:33
  wire         transducer0_errorNoAction =
    transducer0_leftBuffer0_sink_valid & transducer0_cond == 2'h0;	// src/main/scala/accel/bugra/DownSize.scala:44:21, :54:27
  `ifndef SYNTHESIS	// src/main/scala/accel/bugra/DownSize.scala:54:27
    always @(posedge clock) begin	// src/main/scala/accel/bugra/DownSize.scala:54:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:54:27
        $fwrite(32'h80000002,
                "elastic.Transducer: at least two actions are taken in the same clock cycle!\n");	// src/main/scala/accel/bugra/DownSize.scala:54:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE
          & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:54:27, :67:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'accept' @[src/main/scala/accel/bugra/DownSize.scala 54:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:54:27
      if ((`PRINTF_COND_) & transducer0_errorAtLeastTwoActions & _transducer0_WIRE_1
          & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:54:27, :67:33
        $fwrite(32'h80000002,
                "elastic.Transducer: action 'produce' @[src/main/scala/accel/bugra/DownSize.scala 54:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:54:27
      if ((`PRINTF_COND_) & transducer0_errorNoAction & ~reset)	// src/main/scala/accel/bugra/DownSize.scala:54:27
        $fwrite(32'h80000002,
                "elastic.Transducer: no action was taken! @[src/main/scala/accel/bugra/DownSize.scala 54:27]\n");	// src/main/scala/accel/bugra/DownSize.scala:54:27
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// <stdin>:83:11
    if (reset) begin	// <stdin>:83:11
      transducer0_leftBuffer0_wrap <= 1'h0;	// src/main/scala/accel/bugra/DownSize.scala:34:7, src/main/scala/chisel3/util/Counter.scala:61:40
      transducer0_leftBuffer0_wrap_1 <= 1'h0;	// src/main/scala/accel/bugra/DownSize.scala:34:7, src/main/scala/chisel3/util/Counter.scala:61:40
      transducer0_leftBuffer0_maybe_full <= 1'h0;	// src/main/scala/accel/bugra/DownSize.scala:34:7, :44:21
      transducer0_offset <= 1'h0;	// src/main/scala/accel/bugra/DownSize.scala:34:7, :59:25
    end
    else begin	// <stdin>:83:11
      automatic logic transducer0_leftBuffer0_do_deq =
        transducer0_leftBuffer0_sink_ready & transducer0_leftBuffer0_sink_valid;	// src/main/scala/accel/bugra/DownSize.scala:44:21
      if (transducer0_leftBuffer0_do_enq)	// src/main/scala/accel/bugra/DownSize.scala:44:21
        transducer0_leftBuffer0_wrap <= transducer0_leftBuffer0_wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (transducer0_leftBuffer0_do_deq)	// src/main/scala/accel/bugra/DownSize.scala:44:21
        transducer0_leftBuffer0_wrap_1 <= transducer0_leftBuffer0_wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(transducer0_leftBuffer0_do_enq == transducer0_leftBuffer0_do_deq))	// src/main/scala/accel/bugra/DownSize.scala:44:21
        transducer0_leftBuffer0_maybe_full <= transducer0_leftBuffer0_do_enq;	// src/main/scala/accel/bugra/DownSize.scala:44:21
      if (transducer0_leftBuffer0_sink_valid) begin	// src/main/scala/accel/bugra/DownSize.scala:44:21
        if (_transducer0_nextOffset_T) begin	// src/main/scala/accel/bugra/DownSize.scala:60:29
          if (output_TREADY)	// src/main/scala/accel/bugra/DownSize.scala:40:18
            transducer0_offset <= _transducer0_nextOffset_T;	// src/main/scala/accel/bugra/DownSize.scala:59:25, :60:29
        end
        else	// src/main/scala/accel/bugra/DownSize.scala:60:29
          transducer0_offset <= ~output_TREADY & transducer0_offset;	// src/main/scala/accel/bugra/DownSize.scala:59:25, :68:16, :69:18
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/accel/bugra/DownSize.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/accel/bugra/DownSize.scala:34:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/accel/bugra/DownSize.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/DownSize.scala:34:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/accel/bugra/DownSize.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/accel/bugra/DownSize.scala:34:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/accel/bugra/DownSize.scala:34:7
        transducer0_leftBuffer0_wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/accel/bugra/DownSize.scala:34:7, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_leftBuffer0_wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/accel/bugra/DownSize.scala:34:7, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_leftBuffer0_maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/accel/bugra/DownSize.scala:34:7, :44:21, src/main/scala/chisel3/util/Counter.scala:61:40
        transducer0_offset = _RANDOM[/*Zero width*/ 1'b0][3];	// src/main/scala/accel/bugra/DownSize.scala:34:7, :59:25, src/main/scala/chisel3/util/Counter.scala:61:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:34:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/accel/bugra/DownSize.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  chext_mem_1w1r #(
    .ADDR_WIDTH(1),
    .COUNT(2),
    .DATA_WIDTH(256)
  ) transducer0_leftBuffer0_ram (	// src/main/scala/accel/bugra/DownSize.scala:44:21
    .clock    (clock),
    .addrA    (transducer0_leftBuffer0_wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .writeEnA (transducer0_leftBuffer0_do_enq),	// src/main/scala/accel/bugra/DownSize.scala:44:21
    .dataInA  (transducer0_leftBuffer0_source_bits),	// src/main/scala/accel/bugra/DownSize.scala:44:21
    .addrB    (transducer0_leftBuffer0_wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .dataOutB (transducer0_leftBuffer0_sink_bits)
  );
  SteerRight transducer0_steerRight (	// src/main/scala/accel/bugra/DownSize.scala:58:28
    .dataIn   (transducer0_leftBuffer0_sink_bits),	// src/main/scala/accel/bugra/DownSize.scala:44:21
    .offsetIn (transducer0_offset),	// src/main/scala/accel/bugra/DownSize.scala:59:25
    .dataOut  (output_TDATA)
  );
  assign input_TREADY = transducer0_leftBuffer0_source_ready;	// src/main/scala/accel/bugra/DownSize.scala:34:7, :44:21
  assign output_TVALID = transducer0_leftBuffer0_sink_valid;	// src/main/scala/accel/bugra/DownSize.scala:34:7, :44:21
endmodule

module DownSize_256_128(	// src/main/scala/accel/bugra/DownSize.scala:82:7
  input          clock,	// <stdin>:218:11
                 reset_n,	// <stdin>:219:11
  output         input_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:89:17
  input          input_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:89:17
  input  [255:0] input_TDATA,	// src/main/scala/accel/bugra/DownSize.scala:89:17
  input          output_TREADY,	// src/main/scala/accel/bugra/DownSize.scala:90:18
  output         output_TVALID,	// src/main/scala/accel/bugra/DownSize.scala:90:18
  output [127:0] output_TDATA	// src/main/scala/accel/bugra/DownSize.scala:90:18
);

  wire          reset = ~reset_n;	// <stdin>:221:20
  DownSize_Basic_256_128 dut (	// src/main/scala/accel/bugra/DownSize.scala:87:19
    .clock         (clock),
    .reset         (reset),
    .input_TREADY  (input_TREADY),
    .input_TVALID  (input_TVALID),
    .input_TDATA   (input_TDATA),
    .output_TREADY (output_TREADY),
    .output_TVALID (output_TVALID),
    .output_TDATA  (output_TDATA)
  );
endmodule

